# Name of the workflow
name: Unit Tests

# define trigger event(s)
on:
  push:
    branches: [main]
  pull_request:

# jobs run in parallel
jobs:
  docker-unit-tests:
    runs-on: ubuntu-latest
    name: Build and run unit tests Docker image
    steps:

      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t unit-tests-image -f Dockerfile .

      - name: Run Image
        run: docker run --rm unit-tests-image

